### ISSUE TITLE
添加好友为密友后，长按会话tab页的标题，会话栏无法隐藏

### ISSUE THREAD

**Issue by gziqt** [Xposed-Modules-Repo/wx.myfriends#11]
需要把微信后台划掉，重新打开后会话栏会消失，但是此时如果连点五次，已经被隐藏的好友的会话栏也不会出现，需要重新在联系人点开好友，点击发消息，再退出到会话Tab页，好友会话栏才会出现

问题是昨天下午突然出现的

**Comment by gziqt** [comment]
8.0.42版本的微信，插件是1.1.8，后来我升级到1.1.9还是这样

**Comment by 476321234** [comment]
框架用的是哪一个？

**Comment by gziqt** [comment]
> Collaborator

用的是太极

**Comment by gziqt** [comment]
用的太极阴内核，手机没有root




d7335299
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Xposed-Modules-Repo/wx.myfriends"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月13日(星期一) 下午4:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Xposed-Modules-Repo/wx.myfriends] 添加好友为密友后，长按会话tab页的标题，会话栏无法隐藏 (Issue #11)





 
框架用的是哪一个？

**Comment by gziqt** [comment]
> 框架用的是哪一个？

用的太极阴内核，手机没有root
