### ISSUE TITLE
隐藏一位好友后，在通讯录长按另一位好友，菜单没有隐藏好友功能

### ISSUE THREAD

**Issue by NaNMaker** [Xposed-Modules-Repo/wx.myfriends#15]
隐藏一位好友后，在通讯录长按另一位好友，菜单没有隐藏好友功能

**Comment by NaNMaker** [comment]
微信版本8.0.43，微好友1.2.1

**Comment by zhujunsan** [comment]
同，微信 8.0.40，微密友 1.2.2

**Comment by 476321234** [comment]
你需要先“显示好友”（也就是连按三下），然后才会出现菜单；

**Comment by zhujunsan** [comment]
> 你需要先“显示好友”（也就是连按三下），然后才会出现菜单；

你说得对！

**Comment by 476321234** [comment]
1.2.3 版本设置中加入了一个新菜单：显示菜单，开启后无论如何都会显示（不用时建议关闭）。
