### ISSUE TITLE
隐藏密友以后，如何解除设置？

### ISSUE THREAD

**Issue by LHC12580** [Xposed-Modules-Repo/wx.myfriends#21]
另外，隐藏密友后，通知消息能不能设置屏蔽？比如来电视频之类的通知能设置屏蔽吗？
2如果在微信聊天界面 会看到历史遗留聊天记录？还是会全部隐藏文字视图？
3另外麻烦增加可设置，群聊，通信录，搜索密友不可搜索查找，查找不出来密友的效果功能，谢谢

**Comment by 476321234** [comment]
1. 可以屏蔽。
2. 设置中可以开启隐藏聊天记录
3. 本来就支持
