### ISSUE TITLE
朋友圈卡顿

### ISSUE THREAD

**Issue by wecaig** [Xposed-Modules-Repo/wx.myfriends#3]
使用模块后刷朋友圈卡顿，图片视频需要重新加载才能显示。取消激活后问题消失。Android10+LSPosed+MIUI12+微信8.0.41

**Comment by 476321234** [comment]
是否有开启其他的模块，有冲突吗？

**Comment by wecaig** [comment]
> 是否有开启其他的模块，有冲突吗？

只有一个微X，取消激活微X问题还在。需要抓log吗

**Comment by 476321234** [comment]
不需要，我这里复现不了。

**Comment by 476321234** [comment]
> > 是否有开启其他的模块，有冲突吗？
> 
> 只有一个微X，取消激活微X问题还在。需要抓log吗

你试试关闭其他模块，仅仅启用微密友然后重启手机呢？
