### ISSUE TITLE
突然显示未激活 怎么解决哥哥们

### ISSUE THREAD

**Issue by Asd12530** [Xposed-Modules-Repo/wx.myfriends#31]

**Comment by Faker1st** [comment]
我买了永久啊，怎么崩溃了

**Comment by Asd12530** [comment]
我也用不了了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月13日(周一) 下午3:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Xposed-Modules-Repo/wx.myfriends] 突然显示未激活 怎么解决哥哥们 (Issue #31)




 
我买了永久啊，怎么崩溃了

**Comment by Asd12530** [comment]
还能抢救吗这个



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月13日(周一) 下午3:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Xposed-Modules-Repo/wx.myfriends] 突然显示未激活 怎么解决哥哥们 (Issue #31)




 
我买了永久啊，怎么崩溃了

**Comment by 476321234** [comment]
https://github.com/Xposed-Modules-Repo/wx.myfriends/issues/36#issuecomment-2121832970
