### ISSUE TITLE
买了卡密无法使用不知道怎么联系，显示参数错误

### ISSUE THREAD

**Issue by 838562838zx** [Xposed-Modules-Repo/wx.myfriends#4]
![Screenshot_2023-09-19-17-40-16-145_com tencent mm-edit](https://github.com/Xposed-Modules-Repo/wx.myfriends/assets/53548634/57225568-f178-4d25-91b1-05b6b2ee56cf)
![Screenshot_2023-09-19-17-41-32-539_com eg android AlipayGphone](https://github.com/Xposed-Modules-Repo/wx.myfriends/assets/53548634/41b988df-2d68-4ef6-bd11-57118f38f916)

**Comment by 476321234** [comment]
您好，这边发现昨天刚开始确实无法激活；后来过了半小时后已经激活了；经调查确实存在 bug，下次会修复，谢谢你的反馈！

**Comment by 476321234** [comment]
@838562838zx 如果方便的话可否留个邮箱，给您赠送一个卡密，给你造成的不便非常抱歉！

**Comment by 838562838zx** [comment]
嗯嗯，谢谢您。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Xposed-Modules-Repo/wx.myfriends"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月20日(星期三) 中午11:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Xposed-Modules-Repo/wx.myfriends] 买了卡密无法使用不知道怎么联系，显示参数错误 (Issue #4)





 
您好，这边发现昨天刚开始确实无法激活；后来过了半小时后已经激活了；经调查确实存在 bug，下次会修复，谢谢你的反馈！

**Comment by 838562838zx** [comment]
***@***.***






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Xposed-Modules-Repo/wx.myfriends"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月20日(星期三) 中午11:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Xposed-Modules-Repo/wx.myfriends] 买了卡密无法使用不知道怎么联系，显示参数错误 (Issue #4)





 
@838562838zx 如果方便的话可否留个邮箱，给您赠送一个卡密，给你造成的不便非常抱歉！

**Comment by 838562838zx** [comment]
这个就是我的邮箱呀




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Xposed-Modules-Repo/wx.myfriends"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月20日(星期三) 中午11:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Xposed-Modules-Repo/wx.myfriends] 买了卡密无法使用不知道怎么联系，显示参数错误 (Issue #4)





 
@838562838zx 如果方便的话可否留个邮箱，给您赠送一个卡密，给你造成的不便非常抱歉！

**Comment by 476321234** [comment]
> 这个就是我的邮箱呀
> […](#)

不好意思，你这个邮箱里面的东西我这里看不到的
