### ISSUE TITLE
如何购买永久会员，测试期购买是否可以优惠些？

### ISSUE THREAD

**Issue by cclove845** [Xposed-Modules-Repo/wx.myfriends#5]
如何购买永久会员，测试期购买是否可以优惠些？

**Comment by LinYiKing** [comment]
群在哪里 在哪购买 找不到购买入口

**Comment by cclove845** [comment]
> 以及在哪里在哪里购买找不到购买入口

现在有bug买了也没用，隐藏不了

**Comment by 476321234** [comment]
永久会员已添加，购买入口：https://pay.skydesk.ca/prod/h5#/mobile/goodsList?categoryId=miyou

**Comment by LinYiKing** [comment]
好像不支持我的8.0.42_2460 官版

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2023年10月22日 12:15
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Xposed-Modules-Repo/wx.myfriends] 如何购买永久会员，测试期购买是否可以优惠些？ (Issue #5)


永久会员已添加，购买入口：https://pay.skydesk.ca/prod/h5#/mobile/goodsList?categoryId=miyou

―
